from __future__ import annotations


def build_blueprint_registrar_context(
    *,
    blueprint_registry,
    config,
    db_path,
    get_migration_status,
    download_jobs,
    library,
    source_health,
    telemetry,
    qb,
    logger,
    runtime_config_validation,
    test_prowlarr_connection,
    test_qbittorrent_connection,
    test_audiobookshelf_connection,
    test_kavita_connection,
    sources,
    filter_results,
    search_source_safe,
    source_health_metadata,
    truthy,
    download_preflight_response,
    duplicate_summary,
    extract_download_source_id,
    resolve_abb_magnet,
    watch_torrent,
    ensure_retry_scheduler,
    base_job_fields,
    parse_requested_targets,
    start_job_thread,
    download_novel_worker,
    download_annas_worker,
    human_size,
    job_max_retries,
    dispatch_retry,
    run_source_download_worker,
    process_csv_import_jobs,
    get_monitor,
):
    return {
        "blueprint_registry": blueprint_registry,
        "blueprint_deps": {
            "config": config,
            "db_path": db_path,
            "get_migration_status": get_migration_status,
            "download_jobs": download_jobs,
            "library": library,
            "source_health": source_health,
            "telemetry": telemetry,
            "qb": qb,
            "logger": logger,
            "runtime_config_validation": runtime_config_validation,
            "test_prowlarr_connection": test_prowlarr_connection,
            "test_qbittorrent_connection": test_qbittorrent_connection,
            "test_audiobookshelf_connection": test_audiobookshelf_connection,
            "test_kavita_connection": test_kavita_connection,
            "sources": sources,
            "filter_results": filter_results,
            "search_source_safe": search_source_safe,
            "source_health_metadata": source_health_metadata,
            "truthy": truthy,
            "download_preflight_response": download_preflight_response,
            "duplicate_summary": duplicate_summary,
            "extract_download_source_id": extract_download_source_id,
            "resolve_abb_magnet": resolve_abb_magnet,
            "watch_torrent": watch_torrent,
            "ensure_retry_scheduler": ensure_retry_scheduler,
            "base_job_fields": base_job_fields,
            "parse_requested_targets": parse_requested_targets,
            "start_job_thread": start_job_thread,
            "download_novel_worker": download_novel_worker,
            "download_annas_worker": download_annas_worker,
            "human_size": human_size,
            "job_max_retries": job_max_retries,
            "dispatch_retry": dispatch_retry,
            "run_source_download_worker": run_source_download_worker,
            "process_csv_import_jobs": process_csv_import_jobs,
            "get_monitor": get_monitor,
        },
    }


def build_startup_kwargs(
    *,
    app,
    config,
    logger,
    library,
    sources,
    qb,
    opds_module,
    monitor_module,
    ensure_retry_scheduler,
    auto_import_loop,
    validate_config,
    get_jobs,
    get_abb_domains,
    rotate_abb_domain,
    trigger_abs_scan,
):
    return {
        "app": app,
        "config": config,
        "logger": logger,
        "library": library,
        "sources": sources,
        "qb": qb,
        "opds_module": opds_module,
        "monitor_module": monitor_module,
        "ensure_retry_scheduler": ensure_retry_scheduler,
        "auto_import_loop": auto_import_loop,
        "validate_config": validate_config,
        "get_jobs": get_jobs,
        "get_abb_domains": get_abb_domains,
        "rotate_abb_domain": rotate_abb_domain,
        "trigger_abs_scan": trigger_abs_scan,
    }
